# Generated by Django 4.1.7 on 2023-05-09 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('pub_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubs', to=settings.AUTH_USER_MODEL, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Паб',
                'verbose_name_plural': 'Пабы',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol_name', models.CharField(max_length=50, verbose_name='Название')),
                ('alcohol_percent', models.PositiveIntegerField(verbose_name='Процент спирта')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='pubs.pub', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
