# Generated by Django 4.1.7 on 2023-03-16 11:37

from django.db import migrations, models
import django.db.models.deletion
import pubs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[pubs.validators.validate_phone], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Паб',
                'verbose_name_plural': 'Пабы',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubs.pub', verbose_name='Паб')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubs.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Алкоголь',
                'verbose_name_plural': 'Алкоголь',
            },
        ),
    ]
