# Generated by Django 4.1.7 on 2023-04-19 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.AddField(
            model_name='menu',
            name='alcohol',
            field=models.PositiveIntegerField(default=20, verbose_name='Процент спирта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='cost',
            field=models.PositiveIntegerField(default=100, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='sidr', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pub',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pubs', to=settings.AUTH_USER_MODEL, verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='pub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='menus', serialize=False, to='pubs.pub', verbose_name='Паб'),
        ),
        migrations.DeleteModel(
            name='Alcohol',
        ),
    ]
