# Generated by Django 4.1.7 on 2023-05-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
