# Generated by Django 4.1.7 on 2023-04-03 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pubs', '0002_alter_alcohol_menu_alter_menu_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pubs', to=settings.AUTH_USER_MODEL, verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
