# Generated by Django 4.1.7 on 2023-04-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0002_remove_menu_id_menu_alcohol_menu_cost_menu_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='pubs.pub', verbose_name='Паб'),
        ),
    ]
