# Generated by Django 4.1.7 on 2023-05-09 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название комнаты')),
                ('difficulty_level', models.CharField(choices=[('underbeerman', 'Подпивасник'), ('', ''), ('', '')], max_length=50, verbose_name='Уровень сложности')),
                ('budget_level', models.CharField(choices=[('', ''), ('', ''), ('', '')], max_length=50, verbose_name='Уровень бюджета')),
                ('status', models.CharField(choices=[('created', 'Создана комната'), ('started', 'Игра стартовала'), ('finished', 'Игра завершилась')], max_length=50, verbose_name='Статус игры')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время старта игры')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
