# Generated by Django 4.1.7 on 2023-05-16 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='budget_level',
            field=models.CharField(choices=[('homeless', 'Бомж'), ('fan', 'Любитель'), ('major', 'Мажор')], max_length=50, verbose_name='Уровень бюджета'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
    ]
