# Generated by Django 4.1.7 on 2023-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_budget_level_alter_gameuser_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty_level',
            field=models.CharField(choices=[('underbeerman', 'Подпивасник'), ('fan', 'Любитель'), ('freelanholic', 'Фриланголик')], max_length=50, verbose_name='Уровень сложности'),
        ),
    ]
