# Generated by Django 4.1.7 on 2023-05-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='games.game', verbose_name='Комната'),
            preserve_default=False,
        ),
    ]
