# Generated by Django 4.1.7 on 2023-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_invitation_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='player_status',
            field=models.CharField(choices=[('playing', 'Играет'), ('won', 'Выиграл'), ('lost', 'Проиграл')], default='playing', max_length=50, verbose_name='Статус игрока'),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
