# Generated by Django 4.1.7 on 2023-05-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gameuser_player_status_delete_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('created', 'Создана комната'), ('started', 'Игра стартовала'), ('finished', 'Игра завершилась')], default='created', max_length=50, verbose_name='Статус игры'),
        ),
    ]
