# Generated by Django 4.1.7 on 2023-05-22 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='games.GameUser', to=settings.AUTH_USER_MODEL, verbose_name='Игроки'),
        ),
    ]
