# Generated by Django 4.1.7 on 2023-05-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
        ('games', '0009_alter_gameuser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='pub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pubs.pub'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('game', 'pub')},
        ),
    ]
