# Generated by Django 4.1.7 on 2023-06-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
        ('games', '0010_stage_pub_alter_stage_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubs.menu')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.stage')),
            ],
            options={
                'unique_together': {('stage', 'drink')},
            },
        ),
    ]
