# Generated by Django 4.1.7 on 2023-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Аутентифицированный пользователь'), ('company', 'Компания')], default='user', max_length=30, verbose_name='Роль'),
        ),
    ]
