# Generated by Django 4.1.7 on 2023-03-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_photo_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('player', 'Аутентифицированный пользователь'), ('company', 'Компания')], default='player', max_length=30, verbose_name='Роль'),
        ),
    ]
