# Generated by Django 4.1.7 on 2023-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус подтверждения'),
        ),
    ]
